### ISSUE TITLE
Opening files on macOS is broken

### ISSUE THREAD

**Issue by ckirsch** [cksystemsteaching/selfie#180]
@thomaswulz We need to revisit this issue. Opening files on macOS does not work properly anymore. If a file already exists, selfie now appends data to the file rather than overwriting it. Could you please look into this?

**Comment by thomaswulz** [comment]
After doing some testing on a macOS VM, it seems like existing files are actually overwritten from the start, but without getting truncated first. I tried various flag combinations, but unfortunately I was unable to find a sequence of `open` calls that works properly on all OSs.

**Comment by ckirsch** [comment]
@thomaswulz Any other ideas? What exactly is the problem with the original solution?

**Comment by thomaswulz** [comment]
The original code before my PR didn't work properly on Windows as existing files would not be opened in binary mode, so every `\n` would get turned into `\r\n` instead.
Since the flags of the `open` syscall differ so much between platforms, I think it should be possible for selfie to determine the platform it's running on by calling `open` with specific flag values and checking the result. Then, the code in `open_write_only` could just use the result of this check to invoke `open` with the right flags for the current OS instead of trying multiple combinations. Seems a bit hacky though. The only other idea I can think of is to check the platform at compile time using `#ifdef` or something.

**Comment by ckirsch** [comment]
@thomaswulz Yeah, I think we need to do something like that. I'd prefer a solution without `#ifdef`. Since opening files on macOS seems to work for all kinds of flags, the solution may be to use read and write calls. For example, we may open a dummy binary file called, say, `OS` using the flags for macOS, then write to it, and finally read from it to see if the content differs. Then we know if it is Windows or not. If not, we can continue and check if truncation is done or not, to differentiate macOS and Linux.

**Comment by ckirsch** [comment]
Fixed: https://github.com/cksystemsteaching/selfie/commit/6eaeea6d6a7aebd3f2752033d04ea6ff312332a2
