### ISSUE TITLE
1) Introduction - Introductory Assignments

### ISSUE THREAD

**Issue by aemonk** [cksystemsteaching/selfie#201]
- [x] bit
- [x] nibble
- [x] byte
- [x] binary numbers
- [x] decimal
- [x] unary
- [x] octal
- [x] hexadecimal
- [x] How many bits in 6 GB
- [x] Computation
- [x] Software

**Comment by aemonk** [comment]
I started writing descriptions, examples, and exercises. 
It is intended as an example of self-contained content. 
I hope this meets the expectations? @ckirsch

**Comment by ckirsch** [comment]
Looks very nice! Don't forget to spell check.

First and foremost, as far as the computer is concerned, there is no way to move "past numbers" because, to the computer, everything is a number. A computer stores everything as a series of 0's and 1's. This representation is called a bit. A [bit](https://en.wikipedia.org/wiki/Bit) can only have one of two values, which are most commonly represented as either a 0 or 1. The value 1 means high voltage, and the value 0 means low voltage in computer systems.

->

First and foremost, as far as computers are concerned, everything is a number, in fact a binary number. A computer stores everything as a series of 0's and 1's. This representation is called a bit. A [bit](https://en.wikipedia.org/wiki/Bit) can only have one of two values, which are most commonly represented as a 0 and a 1. In actual electronic hardware, value 1 is typically represented by high voltage, and value 0 by low voltage.

**Comment by aemonk** [comment]
Thank you very much for the feedback, I will include it immediately. I will pay more attention to the spellchecker.

**Comment by aemonk** [comment]
Should we make a separate file for each topic? 
Or should everything be in one file?

**Comment by aemonk** [comment]
Hey, @Blazefrost  could you take a look at the file to see if you see any room for improvement?

**Comment by ckirsch** [comment]
> @ckirsch Should we make a separate file for each topic?
> Or should everything be in one file?

everything in one file please. selfie style :)

**Comment by aemonk** [comment]
@ckirsch I finished version 1 of Introductory Assignments.
It would only be important to check that everything is correct.
Maybe @Blazefrost can also take a look at it?

**Comment by ckirsch** [comment]
Looks very nice. Let's talk later today during the group meeting.

**Comment by Blazefrost** [comment]
I've read through the document and I think it looks very nice :+1: 
I've got some very minor nitpicks, though:

- In the chapter "State Space" or "Byte", we could add the smallest/largest (positive) number that a byte can represent. This might even be a good exercise!
- In the subchapter "Decimal to Binary" we could clarify that we divide with the floored result of the previous division.
- You've mentioned ASCII twice without specifying it further. Can we assume that people will be familiar with it in the introduction?

What are your thoughts on these points?

**Comment by ckirsch** [comment]
@Blazefrost Sounds all good. Please go ahead and add your suggestions to the grader branch. Ad ASCII: mention the notion of an ASCII table that maps characters to 7-bit binary numbers.

**Comment by aemonk** [comment]
> @Blazefrost Sounds all good. Please go ahead and add your suggestions to the grader branch. Ad ASCII: mention the notion of an ASCII table that maps characters to 7-bit binary numbers.

@Blazefrost  I found an ASCII table written in Markdown, we could add it to the first topic. It takes up a lot of space since we have over 127 lines.

**Comment by Blazefrost** [comment]
@ckirsch Done!

@aemonk Maybe we could add it as a separate markdown file and link to that, if the usage terms of the Markdown table allow for that. This way everything relevant is in the repo but the assignment markdown will still be lean.

**Comment by aemonk** [comment]
@Blazefrost added the ASCII-table as a separate file and linked it into the introductory-assignments file.
