### ISSUE TITLE
Suggestion: -Werror when self-grading

### ISSUE THREAD

**Issue by kim366** [cksystemsteaching/selfie#265]
When doing the Compiler/Systems assignments, a big focus is put on compiling without warnings. When running the autograder, though, the compilation is not checked for warnings and, as such, it is easy to accidentally submit code with compiler warnings.

My local safety check for this is adding `-Werror` to the `CFLAGS` in the Makefile. This causes self-grading to fail when a warning occurs. If this hinders development, the flag could be added only when compiling through the self-grader.

Would it be possible to use `-Werror` in this repository such that mistakes like this don't happen anymore? Thanks!

**Comment by ckirsch** [comment]
@kim366 Thank you! @ChristianMoesl What do you think?

**Comment by ChristianMoesl** [comment]
@ckirsch I do not know, if we want to include `-Werror` into the CFLAGS. We include 2 big sets of warnings with `-Wall` and `-Wextra`, which can change over time. With `-Werror` every gcc/clang update can potentially break the Selfie build.

Let's imagine, that a new clang version with an additional warning in `-Wall` get's released at the start of a compiler class and it actually breaks the build. You probably do not notice it, because you do not update your compiler every day and also Github does not update their compilers every day in their runners. Then a lot of people would probably be confused, because you give them a project, which doesn't even build.

**Comment by ckirsch** [comment]
@ChristianMoesl How about we only include the option in the grader? Or does the grader already fail if there are warnings?

**Comment by ChristianMoesl** [comment]
The grader uses the Makefile to build Selfie atm. . And it does not care about gcc/clang warnings. It respects selfie warnings though.

**Comment by ckirsch** [comment]
So that would be a nice extension, no? I mean failing if gcc/clang warns. Difficult?

**Comment by ChristianMoesl** [comment]
It's probably not that hard to implement. We can scan the output of the build, much like we do that for the build output of selfie. It really comes down to your preference, if you want that in the grader. Personally I am still undecided, if that is a good thing.

**Comment by ckirsch** [comment]
We could leave the grade as is but report right after the grade that there were bootstrapping warnings that may lead to downgrading.
