### ISSUE TITLE
Grader not terminating on plain selfie

### ISSUE THREAD

**Issue by Sebastian-Landl** [cksystemsteaching/selfie#277]
When executing the grader with `./grader/self.py bitwise-shift-execution` on plain selfie without any modifications the test `right-shift has right RISC-V encoding` does not terminate. Expected behaviour would be grade 5.

**Comment by Blazefrost** [comment]
This seems like a problem in the instruction encoding check. As this is caused by the check and not by the process execution, the execution timeout does not apply. 

In particular, execution of line 148 of `checks.py` takes an exorbitant amount of time:

https://github.com/cksystemsteaching/selfie/blob/e113d85a477779c9d545ff68b31fc1b3b72f8c66/grader/lib/checks.py#L145-L148

Interestingly, while debugging using PDB, it seems like the check determined the code length to be 25,769,803,777 bytes long (approx. 24GiB), which is way off from the the actual size:
![image](https://user-images.githubusercontent.com/8116260/116937754-00829200-ac6a-11eb-921b-70b864b12a82.png)

Furthermore, if Selfie returned a non-zero code, the check would immediately return a failure:

https://github.com/cksystemsteaching/selfie/blob/e113d85a477779c9d545ff68b31fc1b3b72f8c66/grader/lib/checks.py#L124
https://github.com/cksystemsteaching/selfie/blob/e113d85a477779c9d545ff68b31fc1b3b72f8c66/grader/lib/checks.py#L161-L163
--------------

It seems like there is one definitive and potential issue there:

- The instruction encoding check seems to read an invalid code length from the ELF header. This needs some fixing and possibly a refactor.
- Selfie does not terminate with a non-zero return code to indicate compilation issues. Unexpected symbol handling seems somewhat inconsistent as sometimes Selfie does exit with a non-zero code immediately, and some other times Selfie does print a message, but continues compilation.
https://github.com/cksystemsteaching/selfie/blob/e113d85a477779c9d545ff68b31fc1b3b72f8c66/selfie.c#L4435-L4442
https://github.com/cksystemsteaching/selfie/blob/e113d85a477779c9d545ff68b31fc1b3b72f8c66/selfie.c#L4546-L4559

**Comment by ckirsch** [comment]
@Blazefrost Interesting! Does gcc return a non-zero exit code if there were warnings but no errors? In that case we may want to mimic that behavior.

**Comment by Blazefrost** [comment]
I opened a new issue regarding the inconsistent handling of unexpected symbol syntax errors because the underlying problem on the grader is that the code length is parsed incorrectly. The exit code short-circuiting works fine on the grader side, but the exit code may need fixing on the compiler side: #280

**Comment by ChristianMoesl** [comment]
Ah I know, where that bug was introduced. It was introduced, when we separated the code and data segment in the ELF output of Selfie. @Blazefrost are you working on a fix for that? Or should I take care of it?
